name: Build and Deploy
on:
  push:
    branches:
      - main  # or your default branch
  issues:
    types: [opened] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'  # specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Get Issues
      run: node issues.js  # or your specific build command

    - name: Build
      run: npx eleventy  # or your specific build command

    - name: Deploy to gh_pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./_site  # specify the directory of your built site
